from typing import Callable

def initialize() -> None: ...
def task(task: str | Callable) -> None: ...
def cleanup() -> None: ...
def print(msg: str) -> None: ...

class ScopeTimer(): ...
class Graph():
	def add_edge(source: str, target: str): ...
	def print_topological_generations(): ...
class Node():
	def __init__(name: str): ...