from typing import Callable, Optional, Self, List

def cleanup() -> None: ...
def reinit() -> None: ...
def print(msg: str) -> None: ...

def task(task: Callable) -> None: ...
def exec() -> None: ...

class Task():
	pass