from typing import Callable, Optional, Self, List

def cleanup() -> None: ...
def reinit() -> None: ...
def print(msg: str) -> None: ...

def task(task: Callable) -> None: ...
def exec() -> None: ...

def internal_runner(): ...
def run_in_subprocess(): ...

class Task():
	def exec(): ...

class Graph():
	...

class ScopeTimer():
	...