name: auto_graph tests CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Cache Python Build DEBUG
      id: cache-python-build
      uses: actions/cache@v2
      with:
        path: |
          external/cpython/PCbuild/amd64
          external/cpython/Lib/site-packages
        key: python-3.12-debug-${{runner.os}}
        restore-keys: |
          python-3.12-debug-${{runner.os}}

    - name: Build Python 3.12 DEBUG
      if: steps.cache-python-build.outputs.cache-hit != 'true'
      run: |
        external/cpython/PCbuild/build.bat -p x64 -c Debug

    - name: Install pip for custom-built Python
      if: steps.cache-python-build.outputs.cache-hit != 'true'
      run: |
        external/cpython/PCbuild/amd64/python_d.exe -m ensurepip --upgrade
        external/cpython/PCbuild/amd64/python_d.exe -m pip install setuptools --upgrade
  
    - name: Build auto_graph DEBUG
      run: |
        external/cpython/PCbuild/amd64/python_d.exe auto_graph/setup.py build_ext --debug

    - name: Run Python tests
      run: |
        external/cpython/PCBuild/amd64/python_d.exe test_runner.py